/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/pojntfx/saltpanelo/internal/libsaltpanelo */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "bindings.go"

#include "libsaltpanelo_bridge.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void* SaltpaneloNewAdapter(on_request_call_callback onRequestCallCallback, void* onRequestCallUserdata, on_call_disconnected_callback onCallDisconnectedCallback, void* onCallDisconnectedUserdata, on_handle_call_callback onHandleCallCallback, void* onHandleCallUserdata, open_url_callback openURLCallback, void* openURLUserdata, char* raddr, char* ahost, char verbose, int timeout, char* oidcIssuer, char* oidcClientID, char* oidcRedirectURL);
extern char* SaltpaneloAdapterLogin(void* a);
extern char* SaltpaneloAdapterLink(void* a);

/* Return type for SaltpaneloAdapterRequestCall */
struct SaltpaneloAdapterRequestCall_return {
	char r0;
	char* r1;
};
extern struct SaltpaneloAdapterRequestCall_return SaltpaneloAdapterRequestCall(void* a, char* email, char* channelID);
extern char* SaltpaneloAdapterHangupCall(void* a, char* routeID);

#ifdef __cplusplus
}
#endif
