name: CI
on:
  push:
    branches:
      - main
jobs:
  test_phaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly          
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          
      - name: Lint
        run: |
          ls
          cd rusant 
          cargo fmt -- --check
          cargo clippy -- -D warnings          
      - name: Test
        run: |
          cd rusant
          cargo check
          cargo test --all          
      - name: Build
        run: |
          cd rusant 
          cargo build --release    